site_name: Chronos

theme:
  name: 'material'
  font:
    text: Roboto
    code: Roboto Mono
  logo: 'assets/images/logo.png'
  favicon: 'assets/images/favicon.png'
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.sections
    - content.code.copy
    - content.action.edit
    - navigation.footer
  icon:
    repo: fontawesome/brands/github 

repo_url: https://github.com/Chronos-Take-your-time
repo_name: Chronos-Take-your-time

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Chronos-Take-your-time
      name: GitHub
    - icon: material/email
      name: chronosdev@proton.me
      link: mailto:chronosdev@proton.me

extra_css:
  - assets/css/extra.css

extra_javascript:
  - 'https://cdn.jsdelivr.net/npm/@material/mwc-switch@0.22.0/mwc-switch.min.js'
  - 'assets/js/theme-toggle.js'

plugins:
  - search

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - codehilite
  - admonition
